# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Paciente')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('date_schedule', models.DateField(verbose_name='Data do Agendamento')),
                ('date_schedule_start', models.TimeField(verbose_name='Hora início')),
                ('date_schedule_end', models.TimeField(verbose_name='Hora final')),
                ('procedure', models.TextField(blank=True, verbose_name='Procedimento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['date_schedule', 'name', 'date_schedule_start'],
            },
        ),
    ]
